[package]
name = "templates"
version = "0.1.0"
authors = ["MasuqaT <occar@hotmail.co.jp>"]
edition = "2018"

[dev-dependencies]
# Waiting for the update of the original repo
test-case = "1.1.0"

[dependencies]
paste = "0.1"
