[package]
name = "yukicoder"
version = "0.1.0"
authors = ["MasuqaT <occar@hotmail.co.jp>"]
edition = "2018"
publish = false

[dependencies]

[workspace]
members = [
    "level-1_0",
    "level-1_5",
    "level-2_0",
    "level-2_5",
]
